# Generated by Django 5.0.6 on 2024-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="note",
            name="symptoms",
        ),
        migrations.AddField(
            model_name="note",
            name="assessment",
            field=models.ManyToManyField(to="main_app.symptom"),
        ),
    ]
