# Generated by Django 5.0.6 on 2024-06-24 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_symptom_remove_note_symptoms_note_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
