# Generated by Django 5.0.6 on 2024-06-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_note_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(default="On The Hunt", max_length=250),
            preserve_default=False,
        ),
    ]
