# Generated by Django 5.0.6 on 2024-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_note_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
